### ISSUE TITLE
Question: is Axios the best tool for backend calls?

### ISSUE THREAD

**Issue by SteveALee** [nuxt-community/create-nuxt-app#14]
I'm new to nuxt and was thinking of using async / await + Fetch, but axios seems to be the clear favourite in Vue land.

is there a good reason for this?

thanks

**Comment by Atinux** [comment]
Hi @SteveALee 

Axios is well supported, offer many options that are not restricted like `fetch`, also it works both client-side and server-side (for `fetch` you need to add a global polyfill on node.js)

Also, it's only 4,8kB gzipped: https://bundlephobia.com/result?p=axios@0.17.1

**Comment by SteveALee** [comment]
Thanks for the explanations!
