### ISSUE TITLE
Is this updtated with Nuxt 1.0?

### ISSUE THREAD

**Issue by ricardopolo** [nuxt-community/create-nuxt-app#15]

**Comment by clarkdo** [comment]
Resolved by #17

**Comment by ricardopolo** [comment]
@clarkdo it will be allwyas up to dated? I am afraid the releases of the CLI may be slower of the public version

**Comment by clarkdo** [comment]
We will directly use lastest nuxt for cli and keep synchronization between them.

**Comment by egoist** [comment]
@ricardopolo with `nuxt^1.0` you always get latest nuxt
