### ISSUE TITLE
Weird missing dependency

### ISSUE THREAD

**Issue by icebob** [nuxt-community/create-nuxt-app#16]
Hi guys,

I created a project with `create-nuxt-app` and tried to start with `npm run dev` but I got error messages:
```
 ERROR  Failed to compile with 1 errors                                                                    19:52:33

This dependency was not found:

* d:\Work\tmp\nuxt-demo\.nuxt\client.js in multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

To install it, you can run: npm install --save d:\Work\tmp\nuxt-demo\.nuxt\client.js
```

What is the problem? The mentioned "install ...js" message is not valid, I can't install a JS file with `npm install`.

> Win7, Node 8.9.4

Thanks in advance!

**Comment by zhouxinyong** [comment]
the same issue +1

**Comment by Atinux** [comment]
Weird, what are the option you chose?

**Comment by clarkdo** [comment]
Fixed by #17

**Comment by zarapustra** [comment]
today i have same problem 
node 8.9.3
eslint: yes - gives this error

**Comment by clarkdo** [comment]
Fix will be included in next release

**Comment by magick93** [comment]
Is there a workaround?

**Comment by egoist** [comment]
@magick93 fixed already.

**Comment by sudhir600** [comment]
I found the same issue.
where is the fix.. can anyone write step by step guide, please?


![image](https://user-images.githubusercontent.com/4952560/38791957-50e4889a-4168-11e8-805d-c909dec52385.png)

**Comment by clarkdo** [comment]
@sudhir600 
Can you give us more details about your steps and version you are using to reproduce this issue.

**Comment by sudhir600** [comment]
Hi @clarkdo,
I follow Nuxt installation process.
1. downloaded the starter template 
2. Run npm install
3.  and then npm run dev
after that build process show but then a same error occurred.
I am pushing the code in a while.

**Comment by clarkdo** [comment]
@sudhir600 
Your issue is due to lack of dependencies `eslint`, `babel-eslint`, `eslint-loader` and `eslint-plugin-vue` when using `eslint-loader`, you can use `npm` or `yarn` to install them.

```
yarn add eslint babel-eslint eslint-loader eslint-plugin-vue

// or

npm i eslint babel-eslint eslint-loader eslint-plugin-vue
```

I will check the starter-template and I recommend you to use `create-nuxt-app` to generate the project 😄

**Comment by clarkdo** [comment]
@sudhir600 
Actually [starter-template package.json](https://github.com/nuxt-community/starter-template/blob/master/template/package.json#L18-L24) included them, but your project is missing.

**Comment by sudhir600** [comment]
ok.. let me install it.

**Comment by sudhir600** [comment]
Wow.. its working fine now.
Thanks alot @clarkdo
