### ISSUE TITLE
Hot Reloading Issue / This page could not be found

### ISSUE THREAD

**Issue by Duzbee** [nuxt-community/create-nuxt-app#25]
I tried creating apps with each of these configurations (With create-nuxt-app, but I tried without it and I had the same issue after adding a simple error page and a nuxt link to a random page to check the error page):
no custom server framework, no custom UI framework, universal, no axios, no eslint, npm
express, bootstrap, universal, no axios, no eslint, npm

I need to specify that I tried with https only.

After I start the dev server with npm run dev and try to go to the dev server address I see the page and it always refreshes with the following server logs: 
![e857c1ffd95d1e108a2fc97bd8e19f30](https://user-images.githubusercontent.com/16373987/35489336-524513d2-049e-11e8-85de-3d829e977d47.png)

And this chrome console output:
![246e8e711a93c465026aadbc94ff6fbc](https://user-images.githubusercontent.com/16373987/35489398-03b2f0ee-049f-11e8-9bca-7ba06bb6ab68.png)

EDIT: I just tried connecting with the IP and port, not the domain, and it now works perfectly. I think the problem is from the nginx reverse proxy. Here is my configuration:
```
server {
    listen   443 ssl;
    
    ssl on;
    ssl_certificate /etc/nginx/ssl/api/ssl.pem;
    ssl_certificate_key /etc/nginx/ssl/api/ssl.key;

    ssl_session_timeout 5m;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv3:+EXP;
    ssl_prefer_server_ciphers on;

    server_name beta.example.com;
    
    location / {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass              https://localhost:8443;
        proxy_read_timeout      90;
        proxy_redirect          https://localhost:8443 https://beta.example.com;
    }
}
```

**Comment by Duzbee** [comment]
I removed the proxy_redirect and it works perfect now.

**Comment by Duzbee** [comment]
Actually I tried to update nuxt and bootstrap-vue to latest version the the problem appeared again only on the domain. I downgraded them but even before this everytime I tried to access the server through the domain I got a 404 error for /bootstrap.css.map and in the chrome console I get a lot of there errors after a while:
![2d372a25b8fb9add3267feaba3e45870](https://user-images.githubusercontent.com/16373987/35502762-b2834f32-04e6-11e8-895f-20e7e12fb231.png)

**Comment by Duzbee** [comment]
I updated again and added proxy_redirect off; at the top of location / in the nginx config but the bootstrap.css.map error is still there only when connecting through the reverse proxy.

**Comment by Duzbee** [comment]
bootstrap.css.map issue fixed by removing /*# sourceMappingURL=bootstrap.css.map */ from node_modules/bootstrap/dist/css/bootstrap.css. Looks like it's working well now.

**Comment by Duzbee** [comment]
I just tried to add socket.io-client from the with sockets example and I have the first problem again (/_nuxt/...hot-update.json 404 error on dev server and page refresh every second, only on nginx reverse proxy, it works ok with direct ip). Can somebody give me a working nginx reverse proxy config to make this work properly?

**Comment by Duzbee** [comment]
I purged cache and activated development mode in cloudflare and somehow this stopped that error but now I get another one which also doesn't happen on direct IP: 
![b2bfd2df935e42abe34f6b8f0539e3e0](https://user-images.githubusercontent.com/16373987/35563063-29701058-05be-11e8-8af4-21ccbdc27ce0.png)

**Comment by Duzbee** [comment]
Looks like everytime I change something I need to use npm run build otherwise I get errors or the production server doesn't work. I'm really confused.

**Comment by Atinux** [comment]
Hi @Duzbee 

Actually it's due to your proxy, but this has nothing to do with this repo.
