### ISSUE TITLE
How to put all frontend code in a folder ?

### ISSUE THREAD

**Issue by o1lab** [nuxt-community/create-nuxt-app#27]
After creating new nuxt app

```
npx create-nuxt-app <my-project>
```

I placed all frontend related folders (pages, layouts, components..etc) in root folder to a folder named 'client'. I have only three folders on root level now (client, server, node_modules)

On 
```
npm run dev
```

nuxt expects 'pages' folder to be in root folder and throws up an error.

**Comment by Atinux** [comment]
Yes there is @o1lab, it's called `srcDir`: https://nuxtjs.org/api/configuration-srcdir

**Comment by o1lab** [comment]
That is a neat feature.
