### ISSUE TITLE
add buefy to ui framework

### ISSUE THREAD

**Issue by bendo01** [nuxt-community/create-nuxt-app#32]
please add buefy to ui framework
https://buefy.github.io/#/

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/create-nuxt-app/issues/c17">#c17</a>)</em></sub></div>

**Comment by althaffe** [comment]
+1

**Comment by seybsen** [comment]
It was already added with 26b971f
