### ISSUE TITLE
Updating tailwindcss - how?

### ISSUE THREAD

**Issue by stoumann** [nuxt-community/create-nuxt-app#38]
I just started to try this **create-nuxt-app** and were happy to see that i could select **tailwindcss** but i can see that it's an old version and i can't figure out how to update it to the latest version (0.4.1)

Can anyone help me? :)

**UPDATE** - I found out that i can use the node-module instead but why isn't it using this by default?

**Comment by egoist** [comment]
Did something break after updating the dependency?

> I found out that i can use the node-module instead but why isn't it using this by default?

what should be used by default?

**Comment by stoumann** [comment]
Nothing broke by updating the dependency. The dependency wasn't imported in the .nuxt/App.js file - it was a static tailwind.css file instead.

It's probably me who are doing something wrong, but i changed the import in the .nuxt/App.js to the tailwind node-module css instead.
