### ISSUE TITLE
npm run dev fails on npx create-nuxt-app with vuetify

### ISSUE THREAD

**Issue by MalikFaizanZafar** [nuxt-community/create-nuxt-app#44]
![vuetify error](https://user-images.githubusercontent.com/29966551/37591094-2e68cbec-2b8c-11e8-95fe-fb22af4185eb.PNG)

**Comment by OReshetnikov** [comment]
similar wth https://github.com/vuetifyjs/nuxt/issues/33

**Comment by koresar** [comment]
Was fixed with new postcss-loader@2.1.3. This issue is fixed and can be closed.
