### ISSUE TITLE
Creating a new brand project is failing

### ISSUE THREAD

**Issue by Oliboy50** [nuxt-community/create-nuxt-app#48]
### Version

[v1.1.1](https://github.com/nuxt-community/create-nuxt-app/releases/tag/v1.1.1)

### Reproduction link

[http://no-need-for-a-link.example.com](http://no-need-for-a-link.example.com)

### Steps to reproduce

➜  npx create-nuxt-app anime-list-front
npx : 307 installé(s) en 9.648s
> Generating Nuxt.js project in /Users/Oliboy50/anime-list-front
? Project name anime-list-front
? Project description anime-list-front
? Use a custom server framework none
? Use a custom UI framework bulma
? Choose rendering mode Universal
? Use axios module yes
? Use eslint yes
? Author name Oliboy50
? Choose a package manager npm

➜  cd anime-list-front
➜  anime-list-front git:(master) ✗ npm run dev

// it should already work here
// but let's retrying after installing npm dependencies ourselves

➜  anime-list-front git:(master) ✗ npm install
➜  anime-list-front git:(master) ✗ npm run dev

// it still does not work (but with another unrelated error)

### What is expected ?

1) Choosing the "npm" package manager, I shouldn't see "yarn install v0.27.5" (or you should explain why nuxt would need it)

2) "To get started:" section should tell to run "npm install" (or it would be even better to run it itself if possible)

3) After running "npm install" (or not if create-nuxt-app runs it itself), the brand new project should build as expected 
which is not the case, as I still have an issue with a syntax error issue (an object spread operator which requires a bit more babel configuration)

### What is actually happening?

➜  npx create-nuxt-app anime-list-front
npx : 307 installé(s) en 9.648s
> Generating Nuxt.js project in /Users/Oliboy50/anime-list-front
? Project name anime-list-front
? Project description anime-list-front
? Use a custom server framework none
? Use a custom UI framework bulma
? Choose rendering mode Universal
? Use axios module yes
? Use eslint yes
? Author name Oliboy50
? Choose a package manager npm
Initialized empty Git repository in /Users/Oliboy50/anime-list-front/.git/
yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
Done in 0.10s.

  To get started:

    cd anime-list-front
    npm run dev

  To build & start for production:

    cd anime-list-front
    npm run build
    npm start

➜  cd anime-list-front
➜  anime-list-front git:(master) ✗ npm run dev

> anime-list-front@1.0.0 dev /Users/Oliboy50/anime-list-front
> nuxt

sh: nuxt: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! anime-list-front@1.0.0 dev: `nuxt`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the anime-list-front@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Oliboy50/.npm/_logs/2018-03-31T15_38_18_929Z-debug.log

➜  anime-list-front git:(master) ✗ npm install

> fsevents@1.1.3 install /Users/Oliboy50/anime-list-front/node_modules/fsevents
> node install

[fsevents] Success: "/Users/Oliboy50/anime-list-front/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/Oliboy50/anime-list-front/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> nuxt@1.4.0 postinstall /Users/Oliboy50/anime-list-front/node_modules/nuxt
> opencollective postinstall || exit 0

                                                             
                                     :=.                     
                                    -=+=:   :-               
                                  .-=+++=: :++=.             
                                 .-+++++++=++++=.            
                                .=+++++++****++++.           
                               :=+++++++******++*+:          
                              :=+++++++********++*+:         
                             :=+++++++**********++*+-        
                            -=+++++++*************+*+-.      
                          .-=======+**************++++=.     
                          .........::::::::::::::::::::.     
                                         

                          Thanks for installing nuxt 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 106
                              Number of backers: 76
                            Annual budget: US$ 11,539
                            Current balance: US$ 2,794

           👉  Donate: https://opencollective.com/nuxtjs/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

added 1367 packages from 732 contributors in 21.691s

➜  anime-list-front git:(master) ✗ npm run dev

> anime-list-front@1.0.0 dev /Users/Oliboy50/anime-list-front
> nuxt

/Users/Oliboy50/anime-list-front/node_modules/nuxt/lib/core/middleware/nuxt.js:72
      const policies = this.options.render.csp.policies ? 
{...this.options.render.csp.policies} : null
^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Oliboy50/anime-list-front/node_modules/nuxt/lib/core/renderer.js:19:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anime-list-front@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the anime-list-front@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Oliboy50/.npm/_logs/2018-03-31T15_39_43_454Z-debug.log

### Additional comments?

In fact, I think the "..." (from "...this.options.render.csp.policies") is broken in "nuxt" project itself, as I had the same issue on a project built using "starter" template with a old "nuxt" version which I tried to update 
(then it didn't work, and I re-created a new one using "create-nuxt-app" and seeing it still didn't work, I decided to submit an issue... even if it a PITA since I had to authorize "cmty.io" to have full read/write access to everything on my github account and the organizations I belong to...)

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/create-nuxt-app/issues/c30">#c30</a>)</em></sub></div>

**Comment by Oliboy50** [comment]
ok, the `3)` issue is this one => https://github.com/nuxt/nuxt.js/issues/2927

(updating my `nodejs` bin fixed it)

but there's still the `1)` and `2)` issues

**Comment by Atinux** [comment]
Hi @Oliboy50 

This is fixed with v1.2.0, Nuxt 2 will also add back support to node 6.
