### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by factordog** [nuxt-community/create-nuxt-app#55]
### Version

[v1.2.0](https://github.com/nuxt-community/create-nuxt-app/releases/tag/v1.2.0)

### Reproduction link

[https://github.com/factordog/nuxt-blog](https://github.com/factordog/nuxt-blog)

### Steps to reproduce

Run create-nuxt-app <project>
 - no server
- no ui
- No http
- No lint
- install yarn or use npm

Run yarn/npm run dev
- Observer logs in terminal

### What is expected ?

Should generate build and run as expected. This is not working anymore.

### What is actually happening?

Running a fresh create-nuxt-app

Using all defaults, no server, no ui, universal app etc. Just baseline. Keeps throwing an error on yarn/npm run dev:

`Module build failed: Error: No parser and no file path given, couldn't infer a parser.
at normalize (D:\workspace\learning\Vue\Nuxt\nuxt-blog\node_modules\prettier\index.js:7051:13)
at formatWithCursor (D:\workspace\learning\Vue\Nuxt\nuxt-blog\node_modules\prettier\index.js:10370:12)
at D:\workspace\learning\Vue\Nuxt\nuxt-blog\node_modules\prettier\index.js:31115:15
at Object.format (D:\workspace\learning\Vue\Nuxt\nuxt-blog\node_modules\prettier\index.js:31134:12)
at Object.module.exports (D:\workspace\learning\Vue\Nuxt\nuxt-blog\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

@ ./.nuxt/components/nuxt-error.vue 11:0-379
@ ./.nuxt/index.js
@ ./.nuxt/client.js
@ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js`

Worked on previous project, but recently stopped working.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/create-nuxt-app/issues/c38">#c38</a>)</em></sub></div>

**Comment by matt-potter** [comment]
I had this - it's a recent (the last 24 hours) update to the prettier npm package which has broken a lot of things. Forcing prettier to version 1.12.1 will fix. More [here](https://stackoverflow.com/questions/50561649/module-build-failed-error-no-parser-and-no-file-path-given-couldnt-infer-a-p)

**Comment by factordog** [comment]
Fixed! Mildly frustrating. Any chance this will be amended in the vue-loader or waiting for some fix?
