### ISSUE TITLE
Issue running npm dev with tailwind

### ISSUE THREAD

**Issue by bart** [nuxt-community/create-nuxt-app#68]
### Version

[v1.2.0](https://github.com/create-nuxt-app/releases/tag/v1.2.0)

### Reproduction link

[https://codepen.io](https://codepen.io)

### Steps to reproduce

create-nuxt-app myproject

? Project name myproject
? Project description My striking Nuxt.js project
? Use a custom server framework none
? Use a custom UI framework tailwind
? Choose rendering mode Universal
? Use axios module no
? Use eslint no
? Author name Bart
? Choose a package manager yarn

cd myproject
yarn run dev

### What is expected ?

Server starting on localhost:3000

### What is actually happening?

yarn run dev command fails with "MODULE_NOT_FOUND"

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/create-nuxt-app/issues/c46">#c46</a>)</em></sub></div>

**Comment by benbagley** [comment]
+1 Getting this my end as well. Here's my issue https://github.com/nuxt-community/create-nuxt-app/issues/69

**Comment by aldarund** [comment]
Its because https://github.com/nuxt-community/create-nuxt-app/blob/master/template/frameworks/tailwind/tailwind.js#L928 require plugin/container but there no plugin/container after project generated. Remove this import in your project manually and it should work.

**Comment by bart** [comment]
Or I can npm install it, right?

**Comment by aldarund** [comment]
@bart change in resource/tailwindjs it in your generated project 
./plugins/container
to
 'tailwindcss/plugins/container'

**Comment by bart** [comment]
This solves the issue, great! Thanks @aldarund
