### ISSUE TITLE
bash: create-nuxt-app: command not found

### ISSUE THREAD

**Issue by himanshu64** [nuxt-community/create-nuxt-app#81]
dell@Himanshu-sharma:~/Workspace/Web/vue-nuxt$ sudo npm i create-nuxt-app -g[sudo] password for dell:
/home/dell/.npm-global/bin/create-nuxt-app -> /home/dell/.npm-global/lib/node_modules/create-nuxt-app/cli.js
+ create-nuxt-app@1.2.2
added 413 packages in 28.445s
dell@Himanshu-sharma:~/Workspace/Web/vue-nuxt$ create-nuxt-app myapp
bash: create-nuxt-app: command not found

**Comment by potato4d** [comment]
@himanshu64 

Can not solve with the following command?

```bash
$ export PATH="/home/dell/.npm-global/bin:$PATH"
$ create-nuxt-app <project-name>
```

**Comment by himanshu64** [comment]
**solved ,thanks for your help**

**Comment by potato4d** [comment]
@himanshu64 
It was good to solve. Once resolved, please change the state of the ticket to resolved.
