### ISSUE TITLE
Error: Cannot find module 'nuxt-edge'

### ISSUE THREAD

**Issue by jefer590** [nuxt-community/create-nuxt-app#90]
### Version

[v2.0.0](https://github.com/create-nuxt-app/releases/tag/v2.0.0)

### Steps to reproduce

- Update the create-nuxt-app CLI to 2.0.0
- try to create a new project
- use yarn instead of npm
- go to the created folder
- run `yarn dev`
- Throws the error Error: Cannot find module 'nuxt-edge' 

### What is expected ?

Run the newly created project with NuxtJS 2.0

### What is actually happening?

Throwing an error because of a missing dependency: Error: Cannot find module 'nuxt-edge'

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/create-nuxt-app/issues/c64">#c64</a>)</em></sub></div>

**Comment by n1kk** [comment]
Same issue here.
Created new project with feathers/tailwind.
ran `npm i`
ran `npm run dev`
got -> `Error: Cannot find module 'nuxt-edge'`

**Comment by n1kk** [comment]
edited `server/middleware/nuxt.js` line 2
from 
```javascript
const { Nuxt, Builder } = require('nuxt-edge')
```
to 
```javascript
const { Nuxt, Builder } = require('nuxt')
```
and it worked 


tried with another example -> express/tailwind
same issure
file `server/index.js` line 4
```javascript
const { Nuxt, Builder } = require('nuxt-edge')
```

old templates were not updated ?

**Comment by jefer590** [comment]
probably!

There's a PR that fixes that already https://github.com/nuxt-community/create-nuxt-app/issues/90

**Comment by Codefa** [comment]
I think this is all happend because they called the new version 2.0 as nuxt-edge (beta i think )[https://www.npmjs.com/package/nuxt-edge](url) 
and they forgot to fix it and rename it to nuxt

**Comment by Codefa** [comment]
we can fix this issue by installing nuxt-edge simply 

npm i nuxt-edge

Thank you
