### ISSUE TITLE
default template not centeret

### ISSUE THREAD

**Issue by zyxep** [nuxt-community/create-nuxt-app#97]
### Version

[v2.0.1](https://github.com/create-nuxt-app/releases/tag/v2.0.1)

### Reproduction link

[http://localhost:3000](http://localhost:3000)

### Steps to reproduce

  ~/Projects  npx create-nuxt-app test                                                                                                                     993  09:58:27
npx: installed 401 in 8.626s
> Generating Nuxt.js project in /Users/ska/Projects/test
? Project name test
? Project description My hunky-dory Nuxt.js project
? Use a custom server framework none
? Use a custom UI framework tailwind
? Choose rendering mode Universal
? Use axios module no
? Use eslint yes
? Author name Simon K
? Choose a package manager yarn
Initialized empty Git repository in /Users/ska/Projects/test/.git/
yarn install v1.9.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[-----------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/996(node:1557) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/4] 🔗  Linking dependencies...
warning " > eslint-loader@2.1.1" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
warning " > eslint-plugin-vue@4.7.1" has incorrect peer dependency "eslint@^3.18.0 || ^4.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 14.84s.

  To get started:

    cd test
    yarn run dev

  To build & start for production:

    cd test
    yarn run build
    yarn start

  ~/Projects  cd test                                                                                                                                      994  10:00:08
  ~/Projects/test     master   yarn run dev                                                                                                            995  10:00:16
yarn run v1.9.4
$ nuxt

 INFO  Building project

✔ success Builder initialized
✔ success Nuxt files generated

 READY  Listening on http://localhost:3000

### What is expected ?

To have a centeret webpage.

### What is actually happening?

![Screen Shot 2018-09-24 at 10.01.37.png](https://cmty.s3.eu-west-1.amazonaws.com/99351826/fce8ac10-bfdb-11e8-a51e-2d0fd5d9b771.png)

This is from the viewport on Chrome @ MacOS 10.13.6

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/create-nuxt-app/issues/c65">#c65</a>)</em></sub></div>

**Comment by therddlr** [comment]
Now this is some serious issue right here!

**Comment by zyxep** [comment]
i agree :O
